### ISSUE TITLE
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by zhixuanli** [youansheng/torchcv-seg#4]
Thanks for your wonderful code!
When trying to run the bash under script folder, the following error occured:

`subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.`

I have installed the ninja by running `sudo apt-get install ninja-build`.

[This link](https://github.com/zhanghang1989/PyTorch-Encoding/issues/143) says that it's because the pytorch version is 0.4 but not 1.0, but I'm already 1.0.

I don't know how to solve this problem, can you give me some advise?

**Comment by donnyyou** [comment]
uninstall pytorch 1.0 & reinstall pytorch 0.4.1

**Comment by zhixuanli** [comment]
🤣OK!!

**Comment by zhixuanli** [comment]
@youansheng Please have a check of your email box, thank you so much!😊

**Comment by MrLinNing** [comment]
@donnyyou @zhixuanli 
I have installed pytorch 0.4.1, but it still has the same errors.
```
File "/usr/lib/python3.5/subprocess.py", line 708, in run
output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1

....


RuntimeError: Error building extension 'inplace_abn': b'[1/3] c++ -MMD -MF inplace_abn_cpu.o.d -DTORCH_EXTENSION_NAME=inplace_
```
