### ISSUE TITLE
Fix two bugs

### ISSUE THREAD

**Issue by zhixuanli** [youansheng/torchcv-seg#6]
1. 
https://github.com/youansheng/torchcv-seg/blob/master/models/nets/denseassp.py#L67

change 
```
elif isinstance(m, ModuleHelper.BatchNorm2d(bn_type=self.configer.get('network', 'bn_type'))):
```
to
```
elif isinstance(m, type(ModuleHelper.BatchNorm2d(bn_type=self.configer.get('network', 'bn_type')))):
```

2. 
delete this line
https://github.com/youansheng/torchcv-seg/blob/master/models/nets/denseassp.py#L33
```
self.num_features = self.num_features // 2
```
and this line:
https://github.com/youansheng/torchcv-seg/blob/master/models/nets/denseassp.py#L108
```
self.add_module('norm2', ModuleHelper.BatchNorm2d(bn_type=bn_type)(num_features=input_num)),
```

Thanks for your code again!
Have a nice day!! :smile:

**Comment by donnyyou** [comment]
You could submit a pull request. And I will merge it if you're right!
