### ISSUE TITLE
Where the MobileNet V2 pretrained model can be found?

### ISSUE THREAD

**Issue by zhixuanli** [youansheng/torchcv-seg#7]
Where the MobileNet V2 pre-trained model can be found?

Is your version of MobileNet V2 the same with this :
https://github.com/tonylins/pytorch-mobilenet-v2/blob/master/MobileNetV2.py

Thank you!

**Comment by donnyyou** [comment]
You could check the code of this repo.

**Comment by zhixuanli** [comment]
The pre-trained model found and loaded, thank you!
